---
- name: Clone repo, setup virtualenv, and install dependencies
  hosts: all
  become: true
  vars:
    repo_url: "https://github.com/NvnNeha/django_blog.git"
    project_dir: "/home/ubuntu/django_blog/nvnblog"
    env_dir: "/home/ubuntu/projectenv/venv"
    dest_git: "/home/ubuntu/django_blog"
    requirements_path: "/home/ubuntu/django_blog/nvnblog/requirements.txt"

  tasks:

    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone blog_aws repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_git }}"
        version: HEAD
        force: yes
        update: yes

    - name: Create projectenv folder
      file:
        path: "{{ env_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Create virtual environment inside projectenv
      command: python3 -m venv venv
      args:
        chdir: "{{ env_dir }}"

    - name: Install required Python packages from requirements.txt
      pip:
        requirements: "{{ requirements_path }}"
        virtualenv: "{{ env_dir  }}"
        virtualenv_command: python3 -m venv
